### ISSUE TITLE
[bugfix] Some dataset tooltips do not render to values

### ISSUE THREAD

**Issue by abought** [broadinstitute/dig-diabetes-portal#166]
## Summary
Some portal dataset tooltips show code rather than values- see example.
![screen shot 2018-10-03 at 5 19 48 pm](https://user-images.githubusercontent.com/2957073/46440157-8d6eb300-c730-11e8-8dc6-81300f33fa1e.png)

This most often happens for phenotypes that contain special characters, like hyphens.

## Details
When multiple datasets are in use, the plot uses namespaces to locate the correct data. LocusZoom has certain rules for syntax, and only allows limited sets of characters to be used for namespaces. (see [regex](https://github.com/statgen/locuszoom/blob/c4b0be2d5f36416536739b8bcdc322d8f67cf78c/assets/js/app/Layouts.js#L64), alphanumeric + underscores).

## Speculative fix
I do not have a running instance, but the following may help:

Change the [portal datasource creation](https://github.com/broadinstitute/dig-diabetes-portal/blob/c2b8dcffa7977b42e072e8efdf4d0850e5e5b355/web-app/js/lib/dport/locusZoomPlot.js#L1690) code to remove special characters.

```
var source_name = phenotype.replace(/[^A-Za-z0-9_]/g, "")
dataSources.add(source_name, new broadAssociationSource(geneGetLZ, rawPhenotype,dataSetName,propertyName,makeDynamic));
```

You will then need to update layouts to reference the new namespace name correctly (lines of the form `{namespace: { thing1: thing2 }}`- here is [one](https://github.com/broadinstitute/dig-diabetes-portal/blob/c2b8dcffa7977b42e072e8efdf4d0850e5e5b355/web-app/js/lib/dport/locusZoomPlot.js#L1199); there are probably others).

**Comment by benralexander** [comment]
Seems like a good idea, Andy.  We will explore further.

**Comment by abought** [comment]
Thanks, Ben.

To make things easier, the next LZ.js release will add a warning message for situations like this:
https://github.com/statgen/locuszoom/commit/82c4422c675e822f2416bd3051e30c39475f9abc

For now we will only warn, in order to avoid breaking sites like the portal. In later versions I would expect it to throw an error instead.
